[client]
showErrorDetails = "type"
showSidebarNavigation = false

[runner]
magicEnabled = false
fastReruns = false

[server]
runOnSave = true

[theme]
primaryColor = "#274690"
backgroundColor = "#fffaf9"
secondaryBackgroundColor = "#ebe6e5"
textColor = "#527bbf"
# linkColor =
# codeBackgroundColor =
# font = "cool-font, fallback-cool-font, sans-serif"
# codeFont =
# baseRadius =
